services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    env_file:
        - .env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
